=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_json_schema/v1/main_schema_local.json
{
  "$id": "http://ssel.asuscomm.com:9080/v1/main_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "version": "1.0.0",
  "type": "object",
  "properties": {
    "stgy_name": {
      "type": "string"
    },
    "module_name": {
      "type": "string"
    },
    "ga_exec": {
      "type": "boolean"
    },
    "ga_exec_mode": {
        "type": "string",
        "enum": ["BASIC", "ADVANCED", "BEST_EFFORT"]
    },
    "ga_exec_obj": {
        "type": "string",
        "enum": ["PROFIT", "BALANCED"]
    }
    ,
    "bt_start": {
      "type": "string",
      "format": "date-time"
    },
    "bt_end": {
      "type": "string",
      "format": "date-time"
    },
    "markets": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 20
    },
    "ga_markets": {
      "type": "boolean"
    },
    "cdl_type": {
      "type": "integer",
      "enum": [1, 3, 5, 15, 30, 60, 240, 1440]
    },
    "init_balance": {
      "type": "number",
      "minimum": 1000000
    },
    "slippage": {
      "type": "number",
      "minimum": 0.0005,
      "maximum": 0.005
    },
    "bt_times": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^([01]\\d|2[0-3]):59$"
      }
    },
    "vola": {
      "$ref": "strategy_schema.json#/definitions/vola"
    },
    "timeframe": {
      "$ref": "strategy_schema.json#/definitions/timeframe"
    },
    "fixed": {
      "$ref": "strategy_schema.json#/definitions/fixed"
    },
    "weighted": {
      "$ref": "strategy_schema.json#/definitions/weighted"
    },
    "stop_loss": {
      "$ref": "strategy_schema.json#/definitions/stop_loss"
    },
    "trailing_stop": {
      "$ref": "strategy_schema.json#/definitions/trailing_stop"
    },
    "take_profit": {
      "$ref": "strategy_schema.json#/definitions/take_profit"
    },
    "vars": {
      "$ref": "vars_schema.json#/definitions/vars"
    },
    "buy_systems": {
      "$ref": "systems_schema.json#/definitions/systems"
    },
    "buy_system_op": {
      "type": "string"
    },
    "sell_systems": {
      "$ref": "systems_schema.json#/definitions/systems"
    },
    "sell_system_op": {
      "type": "string"
    }
  },

  "required": ["stgy_name", "module_name", "bt_start", "bt_end", "markets","cdl_type", "init_balance", "slippage","vola", "timeframe", "fixed", "weighted", "stop_loss", "trailing_stop","take_profit","vars", "buy_systems", "buy_system_op", "sell_systems", "sell_system_op"]
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/ma_crossover_hdg_vol_mkt_specific_ga.json
{
  "stgy_name": "MACrossOverStrategy",
  "module_name": "MACrossOverStrategy",
  "ga_exec" : true,
  "ga_exec_mode" : "BEST_EFFORT",
  "ga_exec_obj" : "BALANCED",
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2024-11-25T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : ["07:59", "08:59", "16:59", "17:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": true,
    "timeframes": ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                      "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                      "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                      "21:59", "22:59", "23:59"],
    "timegap": 0,
    "ga_timeframes" : true,
    "ga_timegap": [1 , 5]
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "ma0": {"func": "sma", "params": [60], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma1": {"func": "sma", "params": [5], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma2": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma3": {"func": "sma", "params": [5], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma4": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma5": {"func": "sma", "params": [5], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma6": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma7": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma8": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma9": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma10": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma11": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]},
    "ma12": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true,
            "ga_params": [[3,100, "Integer"]], "ga_cdl_types": [60, 240, 1440]}
  },
  "buy_systems": {
    "system0": {"alias": "ma", "left": "close", "op": ">", "right": "ma0"},
    "system1": {"alias": "crossover1", "left": "ma1", "op": ">", "right": "ma2", "market" : "KRW-BTC"},
    "system2": {"alias": "crossover2", "left": "ma3", "op": ">", "right": "ma4", "market" : "KRW-BTC"},
    "system3": {"alias": "crossover3", "left": "ma5", "op": ">", "right": "ma6", "market" : "KRW-ETH"},
    "system4": {"alias": "crossover4", "left": "ma7", "op": ">", "right": "ma8", "market" : "KRW-ETH"},
    "system5": {"alias": "crossover5", "left": "ma9", "op": ">", "right": "ma10", "market" : "KRW-XRP"},
    "system6": {"alias": "crossover6", "left": "ma11", "op": ">", "right": "ma12", "market" : "KRW-XRP"}
  },
  "buy_system_op": "(system0 and (system1 or system2 or system3)) or (not system0 and (system4 or system5 or system6))",
  "sell_systems": {
    "system0": {"alias": "ma", "left": "close", "op": ">", "right": "ma0"},
    "system1": {"alias": "crossover1", "left": "ma1", "op": "<", "right": "ma2", "market" : "KRW-BTC"},
    "system2": {"alias": "crossover2", "left": "ma3", "op": "<", "right": "ma4", "market" : "KRW-BTC"},
    "system3": {"alias": "crossover3", "left": "ma5", "op": "<", "right": "ma6", "market" : "KRW-ETH"},
    "system4": {"alias": "crossover4", "left": "ma7", "op": "<", "right": "ma8", "market" : "KRW-ETH"},
    "system5": {"alias": "crossover5", "left": "ma9", "op": "<", "right": "ma10", "market" : "KRW-XRP"},
    "system6": {"alias": "crossover6", "left": "ma11", "op": "<", "right": "ma12", "market" : "KRW-XRP"}
  },
  "sell_system_op": "(system0 and (system1 or system2 or system3)) or (not system0 and (system4 or system5 or system6))"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/ws_day_hdg_vol_ga2.json
{
  "stgy_name": "WinningSession_Hedge",
  "module_name": "WinningSessionStrategy",
  "ga_exec" : true,
  "ga_exec_mode" : "BASIC",
  "ga_exec_obj" : "PROFIT",
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2023-12-31T08:59:00",
  "markets": ["KRW-ADA","KRW-XRP"],
  "ga_markets" : true,
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.0008,
  "bt_times" : ["08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04,
    "ga_vol_tgt" : [0.02,0.03,0.04]
  },
  "timeframe":{
    "support": true,
    "timeframes": ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                      "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                      "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                      "21:59", "22:59", "23:59"],
    "timegap": 1,
    "ga_timeframes" : true,
    "ga_timegap": [1 , 5]
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4,
    "ga_trade_ratio" : [0.2, 0.6]
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1],
    "ga_top_n" : [[0.3, 0.5], [0.2, 0.3],[0.1, 0.2]]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04,
    "ga_ratio": [-0.1, -0.01]
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02,
    "ga_ratio": [-0.1, -0.01]
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07,
    "ga_ratio": [0.03, 0.1]
  },
  "vars": {
    "ma1": {"func": "sma", "params": [5], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[3,50, "Integer"]], "ga_cdl_types": [60, 240, 1440, 1474], "ga_sources" : ["open", "high", "low", "close"]}
  },
  "buy_systems": {
    "system1": {"alias": "ma1", "left": "close", "op": ">", "right": "ma1"}
  },
  "buy_system_op": "system1",
  "sell_systems": {
    "system1": {"alias": "ma1", "left": "close", "op": "<", "right": "ma1"}
  },
  "sell_system_op": "system1"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/ws_day_vol_ga4.json
{
  "stgy_name": "WinningSession_Day",
  "module_name": "WinningSessionStrategy",
  "ga_exec" : true,
  "ga_exec_mode" : "ADVANCED",
  "ga_exec_obj" : "PROFIT",
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2023-12-31T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "ga_markets" : true,
  "cdl_type": 30,
  "init_balance": 10000000,
  "slippage" : 0.0008,
  "bt_times" : ["08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04,
    "ga_vol_tgt" : [0.02, 0.04]
  },
  "timeframe":{
    "support": false,
    "timeframes": ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                      "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                      "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                      "21:59", "22:59", "23:59"],
    "timegap": 1,
    "ga_timeframes" : true,
    "ga_timegap": [1 , 5]
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4,
    "ga_trade_ratio" : [0.2, 0.6]
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1],
    "ga_top_n" : [[0.3, 0.5], [0.2, 0.3],[0.1, 0.2]]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04,
    "ga_ratio": [-0.1, -0.01]
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.10,
    "ga_ratio": [-0.1, -0.01]
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07,
    "ga_ratio": [0.03, 0.1]
  },
  "vars": {
    "base_time" : "08:59",
    "ga_base_time" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                      "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                      "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                      "21:59", "22:59", "23:59"],
    "base_time2" : "08:59",
    "ga_base_time2" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                      "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                      "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                      "21:59", "22:59", "23:59"],
    "base_time3" : "08:59",
    "ga_base_time3" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                      "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                      "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                      "21:59", "22:59", "23:59"],
    "base_time4" : "08:59",
    "ga_base_time4" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                      "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                      "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                      "21:59", "22:59", "23:59"],
    "sell_time" : "08:59",
    "ga_sell_time" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                  "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                  "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                  "21:59", "22:59", "23:59"],
    "sell_time2" : "08:59",
    "ga_sell_time2" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                  "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                  "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                  "21:59", "22:59", "23:59"],
    "sell_time3" : "08:59",
    "ga_sell_time3" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                  "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                  "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                  "21:59", "22:59", "23:59"],
    "sell_time4" : "08:59",
    "ga_sell_time4" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                  "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                  "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                  "21:59", "22:59", "23:59"],
    "ma": {"func": "sma", "params": [3], "cdl_type": 60, "sources": ["close"], "unary": true,
            "ga_params": [[3,200, "Integer"]], "ga_sources" : ["open", "high", "low", "close"]}
  },
  "buy_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "base_time"},
    "system2": {"alias": "time2", "left": "time", "op": "==", "right": "base_time2"},
    "system3": {"alias": "time3", "left": "time", "op": "==", "right": "base_time"},
    "system4": {"alias": "time4", "left": "time", "op": "==", "right": "base_time2"},
    "system5": {"alias": "ma", "left": "close", "op": ">", "right": "ma"}
  },
  "buy_system_op": "(system1 or system2 or system3 or system4) and system5",
  "sell_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "sell_time"},
    "system2": {"alias": "time2", "left": "time", "op": "==", "right": "sell_time2"},
    "system3": {"alias": "time3", "left": "time", "op": "==", "right": "base_time"},
    "system4": {"alias": "time4", "left": "time", "op": "==", "right": "base_time2"},
    "system5": {"alias": "ma2", "left": "close", "op": "<", "right": "ma"}
  },
  "sell_system_op": "(system1 or system2 or system3 or system4) and system5"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/sws_ma_crossover_hdg_vol_mkt_specific_ga.json
{
  "stgy_name": "SuperWinningSessionPoweredByMACrossOver_Hdge",
  "module_name": "SuperWinningSessionStrategy",
  "ga_exec" : true,
  "ga_exec_mode" : "BEST_EFFORT",
  "ga_exec_obj" : "BALANCED",
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2024-11-25T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "ga_markets" : false,
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : ["08:59", "12:59", "16:59", "20:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": true,
    "timeframes": ["00:59", "04:59", "08:59", "12:59", "16:59", "20:59", "23:59"],
    "timegap": 1,
    "ga_timeframes" : true,
    "ga_timegap": [1 , 5]
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "ma0": {"func": "sma", "params": [3], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "ma1": {"func": "sma", "params": [3], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma2": {"func": "sma", "params": [5], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma3": {"func": "sma", "params": [10], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma4": {"func": "sma", "params": [20], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma5": {"func": "sma", "params": [20], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma6": {"func": "sma", "params": [60], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma7": {"func": "sma", "params": [7], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma8": {"func": "sma", "params": [15], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma9": {"func": "sma", "params": [15], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma10": {"func": "sma", "params": [20], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma11": {"func": "sma", "params": [60], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma12": {"func": "sma", "params": [7], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma13": {"func": "sma", "params": [15], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]},
    "ma14": {"func": "sma", "params": [15], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,100, "Integer"]]}
  },
  "buy_systems": {
    "system0": {"alias": "ma0", "left": "close", "op": ">", "right": "ma0", "market" : "KRW-BTC"},
    "system1": {"alias": "ma1", "left": "close", "op": ">", "right": "ma1", "market" : "KRW-BTC"},
    "system2": {"alias": "ma2", "left": "close", "op": ">", "right": "ma2", "market" : "KRW-BTC"},
    "system3": {"alias": "ma3", "left": "close", "op": ">", "right": "ma3", "market" : "KRW-BTC"},
    "system4": {"alias": "ma4", "left": "close", "op": ">", "right": "ma4", "market" : "KRW-BTC"},
    "system5": {"alias": "crossover1", "left": "ma2", "op": ">", "right": "ma4", "market" : "KRW-BTC"},
    "system6": {"alias": "ma5", "left": "close", "op": ">", "right": "ma5", "market" : "KRW-ETH"},
    "system7": {"alias": "ma6", "left": "close", "op": ">", "right": "ma6", "market" : "KRW-ETH"},
    "system8": {"alias": "ma7", "left": "close", "op": ">", "right": "ma7", "market" : "KRW-ETH"},
    "system9": {"alias": "ma8", "left": "close", "op": ">", "right": "ma8", "market" : "KRW-ETH"},
    "system10": {"alias": "ma9", "left": "close", "op": ">", "right": "ma9", "market" : "KRW-ETH"},
    "system11": {"alias": "crossover2", "left": "ma7", "op": ">", "right": "ma9", "market" : "KRW-ETH"},
    "system12": {"alias": "ma10", "left": "close", "op": ">", "right": "ma10", "market" : "KRW-XRP"},
    "system13": {"alias": "ma11", "left": "close", "op": ">", "right": "ma11", "market" : "KRW-XRP"},
    "system14": {"alias": "ma12", "left": "close", "op": ">", "right": "ma12", "market" : "KRW-XRP"},
    "system15": {"alias": "ma13", "left": "close", "op": ">", "right": "ma13", "market" : "KRW-XRP"},
    "system16": {"alias": "ma14", "left": "close", "op": ">", "right": "ma14", "market" : "KRW-XRP"},
    "system17": {"alias": "crossover2", "left": "ma12", "op": ">", "right": "ma14", "market" : "KRW-XRP"}
  },
  "buy_system_op": "(system0 and system1 and system2 and system3 and system4 and system5) or (system6 and system7 and system8 and system9 and system10 and system11) or (system12 and system13 and system14 and system15 and system16 and system17)",
  "sell_systems": {
    "system0": {"alias": "ma0", "left": "close", "op": ">", "right": "ma0", "market" : "KRW-BTC"},
    "system1": {"alias": "ma1", "left": "close", "op": "<", "right": "ma1", "market" : "KRW-BTC"},
    "system2": {"alias": "ma2", "left": "close", "op": "<", "right": "ma2", "market" : "KRW-BTC"},
    "system3": {"alias": "ma3", "left": "close", "op": "<", "right": "ma3", "market" : "KRW-BTC"},
    "system4": {"alias": "ma4", "left": "close", "op": "<", "right": "ma4", "market" : "KRW-BTC"},
    "system5": {"alias": "crossover1", "left": "ma2", "op": "<", "right": "ma4", "market" : "KRW-BTC"},
    "system6": {"alias": "ma5", "left": "close", "op": ">", "right": "ma5", "market" : "KRW-ETH"},
    "system7": {"alias": "ma6", "left": "close", "op": "<", "right": "ma6", "market" : "KRW-ETH"},
    "system8": {"alias": "ma7", "left": "close", "op": "<", "right": "ma7", "market" : "KRW-ETH"},
    "system9": {"alias": "ma8", "left": "close", "op": "<", "right": "ma8", "market" : "KRW-ETH"},
    "system10": {"alias": "ma9", "left": "close", "op": "<", "right": "ma9", "market" : "KRW-ETH"},
    "system11": {"alias": "crossover2", "left": "ma7", "op": "<", "right": "ma9", "market" : "KRW-ETH"},
    "system12": {"alias": "ma10", "left": "close", "op": ">", "right": "ma10", "market" : "KRW-XRP"},
    "system13": {"alias": "ma11", "left": "close", "op": "<", "right": "ma11", "market" : "KRW-XRP"},
    "system14": {"alias": "ma12", "left": "close", "op": "<", "right": "ma12", "market" : "KRW-XRP"},
    "system15": {"alias": "ma13", "left": "close", "op": "<", "right": "ma13", "market" : "KRW-XRP"},
    "system16": {"alias": "ma14", "left": "close", "op": "<", "right": "ma14", "market" : "KRW-XRP"},
    "system17": {"alias": "crossover2", "left": "ma12", "op": "<", "right": "ma14", "market" : "KRW-XRP"}
  },
  "sell_system_op": "(not system0 and (system1 or system2 or system3 or system4 or system5)) or (not system6 and (system7 or system8 or system9 or system10 or system11)) or (not system12 and (system13 or system14 or system15 or system16 or system17))"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/swkim_1_hdg_vol_mkt_specific_ga.json
{
  "stgy_name": "SWKimStrategy1_Hdge",
  "module_name": "SWKimStrategy",
  "ga_exec" : true,
  "ga_exec_mode" : "BEST_EFFORT",
  "ga_exec_obj" : "BALANCED",
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2024-11-25T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "ga_markets" : false,
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : ["08:59", "16:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.02
  },
  "timeframe":{
    "support": true,
    "timeframes": ["00:59", "04:59", "08:59", "12:59", "16:59", "20:59", "23:59"],
    "timegap": 1,
    "ga_timeframes" : true,
    "ga_timegap": [1 , 5]
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "ma0": {"func": "sma", "params": [3], "cdl_type": 1474, "sources": ["close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "pdi1": {"func": "PLUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "mdi1": {"func": "MINUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "pdi2": {"func": "PLUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "mdi2": {"func": "MINUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "pdi3": {"func": "PLUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "mdi3": {"func": "MINUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "pdi4": {"func": "PLUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "mdi4": {"func": "MINUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "pdi5": {"func": "PLUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "mdi5": {"func": "MINUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "pdi6": {"func": "PLUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]},
    "mdi6": {"func": "MINUS_DI", "params": [14], "cdl_type": 240, "sources": ["high","low","close"], "unary": true,
            "ga_params": [[5,200, "Integer"]]}
  },
  "buy_systems": {
    "system0": {"alias": "ma0", "left": "close", "op": ">", "right": "ma0"},
    "system1": {"alias": "di1", "left": "pdi1", "op": ">", "right": "mdi1", "market" : "KRW-BTC"},
    "system2": {"alias": "di2", "left": "pdi2", "op": ">", "right": "mdi2", "market" : "KRW-ETH"},
    "system3": {"alias": "di3", "left": "pdi3", "op": ">", "right": "mdi3", "market" : "KRW-XRP"},
    "system4": {"alias": "di4", "left": "pdi4", "op": ">", "right": "mdi4", "market" : "KRW-BTC"},
    "system5": {"alias": "di5", "left": "pdi5", "op": ">", "right": "mdi5", "market" : "KRW-ETH"},
    "system6": {"alias": "di6", "left": "pdi6", "op": ">", "right": "mdi6", "market" : "KRW-XRP"}
  },
  "buy_system_op": "(system0 and (system1 or system2 or system3)) or (not system0 and (system4 or system5 or system6))",
  "sell_systems": {
    "system0": {"alias": "ma0", "left": "close", "op": ">", "right": "ma0"},
    "system1": {"alias": "di1", "left": "pdi1", "op": "<", "right": "mdi1", "market" : "KRW-BTC"},
    "system2": {"alias": "di2", "left": "pdi2", "op": "<", "right": "mdi2", "market" : "KRW-BTC"},
    "system3": {"alias": "di3", "left": "pdi3", "op": "<", "right": "mdi3", "market" : "KRW-ETH"},
    "system4": {"alias": "di4", "left": "pdi4", "op": "<", "right": "mdi4", "market" : "KRW-ETH"},
    "system5": {"alias": "di5", "left": "pdi5", "op": "<", "right": "mdi5", "market" : "KRW-XRP"},
    "system6": {"alias": "di6", "left": "pdi6", "op": "<", "right": "mdi6", "market" : "KRW-XRP"}
  },
  "sell_system_op": "(system0 and (system1 or system2 or system3)) or (not system0 and (system4 or system5 or system6))"
}
