=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_json_schema/v03/main_schema_remote.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "version": "1.0.0",
  "properties": {
    "stgy_name": {
      "type": "string"
    },
    "module_name": {
      "type": "string"
    },
    "ga_exec": {
      "type": "boolean"
    },
    "ga_exec_mode": {
        "type": "string",
        "enum": ["BASIC", "ADVANCED", "BEST_EFFORT"]
    },
    "ga_exec_obj": {
        "type": "string",
        "enum": ["PROFIT", "BALANCED"]
    },
    "pt_exec": {
      "type": "boolean"
    },
    "bt_start": {
      "type": "string",
      "format": "date-time"
    },
    "bt_end": {
      "type": "string",
      "format": "date-time"
    },
    "markets": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 20
    },
    "ga_markets": {
      "type": "boolean"
    },
    "cdl_type": {
      "type": "integer",
      "enum": [1, 3, 5, 15, 30, 60, 240, 1440]
    },
    "init_balance": {
      "type": "number",
      "minimum": 1000000
    },
    "slippage": {
      "type": "number",
      "minimum": 0.0005,
      "maximum": 0.02
    },
    "bt_times": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^([01]\\d|2[0-3]):59$"
      }
    },
    "vola": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/vola"
    },
    "timeframe": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/timeframe"
    },
    "fixed": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/fixed"
    },
    "weighted": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/weighted"
    },
    "stop_loss": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/stop_loss"
    },
    "trailing_stop": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/trailing_stop"
    },
    "take_profit": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/take_profit"
    },
    "reserved_vars" :{
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0
    },
    "vars": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/vars_schema.json#/definitions/vars"
    },
    "buy_sell_systems_pt_ga" : {
      "$ref": "http://ssel.asuscomm.com:9080/v1/systems_schema.json#/definitions/buy_sell_systems_pt_ga"
    },
    "buy_systems": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/systems_schema.json#/definitions/systems"
    },
    "buy_system_op": {
      "type": "string"
    },
    "sell_systems": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/systems_schema.json#/definitions/systems"
    },
    "sell_system_op": {
      "type": "string"
    }
  },

  "required": ["stgy_name", "module_name", "bt_start", "bt_end", "markets","cdl_type", "init_balance", "slippage","vola", "timeframe", "fixed", "weighted", "stop_loss", "trailing_stop","take_profit","vars", "buy_systems", "buy_system_op"]
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/sws_ma_crossover_day_vol_pair_trading.json
{
  "stgy_name": "SuperWinningSessionPoweredByMACrossOver_Day",
  "module_name": "SuperWinningSessionStrategy",
  "pt_exec" : true,
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2022-11-25T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : ["07:59", "08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": false,
    "timeframes": ["7:59", "8:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "base_time" : "08:59",
    "sell_time" : "07:59",
    "ma1": {"func": "sma", "params": [3], "cdl_type": 1440, "sources": ["close"], "unary": true},
    "ma2": {"func": "sma", "params": [5], "cdl_type": 1440, "sources": ["close"], "unary": true},
    "ma3": {"func": "sma", "params": [10], "cdl_type": 1440, "sources": ["close"], "unary": true},
    "ma4": {"func": "sma", "params": [20], "cdl_type": 1440, "sources": ["close"], "unary": true
    }},
  "buy_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "base_time"},
    "system2": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system3": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system4": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system5": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system6": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system7": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma1","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system8": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma2","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system9": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma3","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system10": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system11": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"}
  },
  "buy_system_op": "system1 and ((system2 and system3 and system4 and system5 and system6) or (system7 and system8 and system9 and system10 and system11))",
  "sell_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "sell_time"},
    "system2": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system3": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system4": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system5": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system6": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system7": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma1","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system8": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma2","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system9": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma3","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system10": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system11": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"}
  },
  "sell_system_op": "system1 and ((system2 or system3 or system4 or system5 or system6) or (system7 or system8 or system9 or system10 or system11))"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/sws_day_hdg_vol_tai_pair_trading.json
{
  "stgy_name": "SuperWinningSession_TAI_Hedge",
  "module_name": "SuperWinningSessionStrategy",
  "pt_exec" : true,
  "bt_start": "2023-01-24T08:59:00",
  "bt_end": "2023-05-14T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : ["08:59", "17:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": true,
    "timeframes": ["08:59", "17:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "ma1": {"func": "sma", "params": [3], "cdl_type": 1474, "sources": ["close"], "unary": true},
    "ma2": {"func": "sma", "params": [5], "cdl_type": 1474, "sources": ["close"], "unary": true},
    "ma3": {"func": "sma", "params": [10], "cdl_type": 1474, "sources": ["close"], "unary": true},
    "ma4": {"func": "sma", "params": [20], "cdl_type": 1474, "sources": ["close"], "unary": true},
    "macd": {"func": "macd", "params": [12, 26, 9], "cdl_type": 1474, "sources": ["close"], "unary": false},
    "cci": {"func": "cci", "params": [], "cdl_type": 1474, "sources": ["high", "low", "close"], "unary": true},
    "bb": {"func": "bbands", "params": [20, 4.0, 2.0, 0], "cdl_type": 1474, "sources": ["close"], "unary": false}
  },
  "buy_systems": {
    "system1": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": ">", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system2": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": ">", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system3": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": ">", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system4": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": ">", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system5": {"alias": "macd", "left": "macd[0]", "pt_left_market" : "KRW-BTC" ,"op": ">", "right": "macd[1]","pt_right_market" : "KRW-BTC", "pt_tgt_market" : "KRW-ETH"},
    "system6": {"alias": "cci", "left": "cci", "pt_left_market" : "KRW-BTC" ,"op": ">", "right": "0","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system7": {"alias": "bb", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": ">", "right": "bb[2]", "pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system8": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": ">", "right": "ma1","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system9": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": ">", "right": "ma2","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system10": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": ">", "right": "ma3","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system11": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": ">", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system12": {"alias": "macd", "left": "macd[0]", "pt_left_market" : "KRW-ETH" ,"op": ">", "right": "macd[1]","pt_right_market" : "KRW-ETH", "pt_tgt_market" : "KRW-XRP"},
    "system13": {"alias": "cci", "left": "cci", "pt_left_market" : "KRW-ETH" ,"op": ">", "right": "0","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system14": {"alias": "bb", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": ">", "right": "bb[2]", "pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"}
  },
  "buy_system_op": "(system1 and system2 and system3 and system4 and system5 and system6 and system7) or (system8 and system9 and system10 and system11 and system12 and system13 and system14)",
  "sell_systems": {
    "system1": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": "<", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system2": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": "<", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system3": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": "<", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system4": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": "<", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system5": {"alias": "macd", "left": "macd[0]", "pt_left_market" : "KRW-BTC" ,"op": "<", "right": "macd[1]","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system6": {"alias": "cci", "left": "cci", "pt_left_market" : "KRW-BTC" ,"op": "<", "right": "0","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system7": {"alias": "bb", "left": "close", "pt_left_market" : "KRW-BTC" ,"op": ">", "right": "bb[0]","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system8": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": "<", "right": "ma1","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system9": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": "<", "right": "ma2","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system10": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": "<", "right": "ma3","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system11": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": "<", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system12": {"alias": "macd", "left": "macd[0]", "pt_left_market" : "KRW-ETH" ,"op": "<", "right": "macd[1]","pt_right_market" : "KRW-ETH", "pt_tgt_market" : "KRW-XRP"},
    "system13": {"alias": "cci", "left": "cci", "pt_left_market" : "KRW-ETH" ,"op": "<", "right": "0","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system14": {"alias": "bb", "left": "close", "pt_left_market" : "KRW-ETH" ,"op": ">", "right": "bb[0]", "pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"}
  },
  "sell_system_op": "(system1 or system2 or system3 or system4 or system5 or system6 or system7) or (system8 or system9 or system10 or system11 or system12 or system13 or system14)"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/vol_bout_vol_pair_trading.json
{
  "stgy_name": "VolatilityBreakoutStrategy",
  "module_name": "VolatilityBreakoutStrategy",
  "pt_exec" : true,
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2022-11-25T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : [],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": false,
    "timeframes": ["07:59", "08:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "reserved_vars" : ["open_d1"],
  "vars": {
    "base_time" : "08:59",
    "sell_time" : "07:59",
    "range": {"func": "range", "params": [1], "cdl_type": 1440, "sources": ["high","low"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "k", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "open_d1 + range * 0.5","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "buy_system_op": "system1",
  "sell_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "sell_time"}
  },
  "sell_system_op": "system1"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/bb_bullish_bearish_reversal_hdg_vol_pair_trading.json
{
  "stgy_name": "WinningSession_Day",
  "module_name": "WinningSessionStrategy",
  "pt_exec" : true,
  "bt_start": "2020-01-01T08:59:00",
  "bt_end": "2022-03-31T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH"],
  "cdl_type": 60,
  "init_balance": 5000000,
  "slippage" : 0.0005,
  "bt_times" : ["08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": true,
    "timeframes": ["08:59", "17:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": true,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.10
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "bbands": {"func": "bbands", "params": [25, 2.0, 2.0, 0], "cdl_type": 1474, "sources": ["close"], "unary": false},
    "bullish_rev":{"func": "bullish_reversal", "params": [15], "cdl_type": 1474,"sources": ["bbands[2]"], "unary": true},
    "bearish_rev":{"func": "bearish_reversal", "params": [15], "cdl_type": 1474,"sources": ["bbands[0]"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "bullish_rev", "left": "bullish_rev",  "pt_left_market" : "KRW-BTC", "op": "==", "right": "True","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "buy_system_op": "system1",
  "sell_systems": {
    "system1": {"alias": "bearish_rev", "left": "bearish_rev", "pt_left_market" : "KRW-BTC", "op": "==", "right": "True", "pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "sell_system_op": "system1"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/ma_crossover_hdg_vol_pair_trading.json
{
  "stgy_name": "MACrossOverStrategy",
  "module_name": "MACrossOverStrategy",
  "pt_exec" : true,
  "bt_start": "2022-10-01T08:59:00",
  "bt_end": "2023-12-31T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : ["07:59", "08:59", "16:59", "17:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": true,
    "timeframes": ["08:59", "17:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "ma1": {"func": "sma", "params": [5], "cdl_type": 240, "sources": ["close"], "unary": true},
    "ma2": {"func": "sma", "params": [20], "cdl_type": 240, "sources": ["close"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "band", "left": "ma1", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma2 * (1+0.01)",
                "pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system2": {"alias": "band", "left": "ma1", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma2 * (1+0.01)",
                "pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system3": {"alias": "band", "left": "ma1", "pt_left_market" : "KRW-XRP", "op": ">", "right": "ma2 * (1+0.01)",
                "pt_right_market" :  "KRW-XRP", "pt_tgt_market" :  "KRW-BTC"}
  },
  "buy_system_op": "system1 or system2 or system3",
  "sell_systems": {
    "system1": {"alias": "band", "left": "ma1", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma2 * (1-0.01)",
                "pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system2": {"alias": "band", "left": "ma1", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma2 * (1-0.01)",
                "pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-XRP"},
    "system3": {"alias": "band", "left": "ma1", "pt_left_market" : "KRW-XRP", "op": "<", "right": "ma2 * (1-0.01)",
                "pt_right_market" :  "KRW-XRP", "pt_tgt_market" :  "KRW-BTC"}
  },
  "sell_system_op": "system1 or system2 or system3"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/swkim_1_hdg_vol_pair_trading.json
{
  "stgy_name": "SWKimStrategy1_Hdge",
  "module_name": "SWKimStrategy",
  "pt_exec" : true,
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2022-11-25T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : ["07:59","08:59", "15:59","16:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.02
  },
  "timeframe":{
    "support": true,
    "timeframes": ["08:59", "16:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "pdi": {"func": "PLUS_DI", "params": [14], "cdl_type": 1474, "sources": ["high","low","close"], "unary": true},
    "mdi": {"func": "MINUS_DI", "params": [14], "cdl_type": 1474, "sources": ["high","low","close"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "di", "left": "pdi", "pt_left_market" : "KRW-BTC", "op": ">", "right": "mdi","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "buy_system_op": "system1",
  "sell_systems": {
    "system1": {"alias": "di", "left": "pdi", "pt_left_market" : "KRW-BTC", "op": "<", "right": "mdi","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "sell_system_op": "system1"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/sws_4h_vol_pair_trading.json
{
  "stgy_name": "SuperWinningSession_4H",
  "module_name": "SuperWinningSessionStrategy",
  "pt_exec" : true,
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2023-12-31T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.0008,
  "bt_times" : ["00:59", "04:59", "08:59", "12:59", "16:59", "20:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.028884725757829813
  },
  "timeframe":{
    "support": false,
    "timeframes": ["00:59", "04:59", "08:59", "12:59", "16:59", "20:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "trade_time1" : "00:59",
    "trade_time2" : "04:59",
    "trade_time3" : "08:59",
    "trade_time4" : "12:59",
    "trade_time5" : "16:59",
    "trade_time6" : "20:59",
    "ma1": {"func": "sma", "params": [5], "cdl_type": 1440, "sources": ["open"], "unary": true},
    "ma2": {"func": "sma", "params": [20], "cdl_type": 1440, "sources": ["close"], "unary": true},
    "ma3": {"func": "sma", "params": [18], "cdl_type": 1440, "sources": ["high"], "unary": true},
    "ma4": {"func": "sma", "params": [43], "cdl_type": 1440, "sources": ["high"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "trade_time1"},
    "system2": {"alias": "time", "left": "time", "op": "==", "right": "trade_time2"},
    "system3": {"alias": "time", "left": "time", "op": "==", "right": "trade_time3"},
    "system4": {"alias": "time", "left": "time", "op": "==", "right": "trade_time4"},
    "system5": {"alias": "time", "left": "time", "op": "==", "right": "trade_time5"},
    "system6": {"alias": "time", "left": "time", "op": "==", "right": "trade_time6"},
    "system7": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system8": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system9": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system10": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "buy_system_op": "(system1 or system2 or system3 or system4 or system5 or system6) and system7 and system8 and system9 and system10",
  "sell_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "trade_time1"},
    "system2": {"alias": "time", "left": "time", "op": "==", "right": "trade_time2"},
    "system3": {"alias": "time", "left": "time", "op": "==", "right": "trade_time3"},
    "system4": {"alias": "time", "left": "time", "op": "==", "right": "trade_time4"},
    "system5": {"alias": "time", "left": "time", "op": "==", "right": "trade_time5"},
    "system6": {"alias": "time", "left": "time", "op": "==", "right": "trade_time6"},
    "system7": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system8": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system9": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system10": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "sell_system_op": "(system1 or system2 or system3 or system4 or system5 or system6) and system7 and system8 and system9 and system10"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/bb_breakout_pair_trading.json
{
  "stgy_name": "WinningSession_Day",
  "module_name": "WinningSessionStrategy",
  "pt_exec" : true,
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2023-12-31T08:59:00",
  "markets": ["KRW-BTC","KRW-ETH"],
  "cdl_type": 60,
 "init_balance": 10000000,
  "slippage" : 0.0008,
 "bt_times" : ["08:59", "13:59", "20:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.0383862786785994
  },
  "timeframe":{
    "support": false,
    "timeframes": ["07:59", "08:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": true,
    "ratio": -0.030115134150950074
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.10
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "base_time" : "13:59",
    "sell_time" : "20:59",
    "bbands": {"func": "bbands", "params": [100, 3.388575337999478, 2.146048750784143, 1], "cdl_type": 1440, "sources": ["open"], "unary": false},
    "up_breakout":  {"func": "up_breakout_vals", "params": [16], "cdl_type": 1440,"sources": ["close", "bbands[2]"], "unary": true},
    "down_breakout":{"func": "down_breakout_vals", "params": [44], "cdl_type": 1440,"sources": ["close", "bbands[0]"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "base_time"},
    "system2": {"alias": "up_breakout", "left": "up_breakout", "pt_left_market" : "KRW-BTC", "op": "==", "right": "True", "pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "buy_system_op": "system1 and system2",
  "sell_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "sell_time"},
    "system2": {"alias": "down_breakout", "left": "down_breakout", "pt_left_market" : "KRW-BTC", "op": "==", "right": "True", "pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"}
  },
  "sell_system_op": "system1 and system2"
}
