=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_json_schema/v03/main_schema_remote.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "version": "1.0.0",
  "properties": {
    "stgy_name": {
      "type": "string"
    },
    "module_name": {
      "type": "string"
    },
    "ga_exec": {
      "type": "boolean"
    },
    "ga_exec_mode": {
        "type": "string",
        "enum": ["BASIC", "ADVANCED", "BEST_EFFORT"]
    },
    "ga_exec_obj": {
        "type": "string",
        "enum": ["PROFIT", "BALANCED"]
    },
    "pt_exec": {
      "type": "boolean"
    },
    "bt_start": {
      "type": "string",
      "format": "date-time"
    },
    "bt_end": {
      "type": "string",
      "format": "date-time"
    },
    "markets": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 20
    },
    "ga_markets": {
      "type": "boolean"
    },
    "cdl_type": {
      "type": "integer",
      "enum": [1, 3, 5, 15, 30, 60, 240, 1440]
    },
    "init_balance": {
      "type": "number",
      "minimum": 1000000
    },
    "slippage": {
      "type": "number",
      "minimum": 0.0005,
      "maximum": 0.02
    },
    "bt_times": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^([01]\\d|2[0-3]):59$"
      }
    },
    "vola": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/vola"
    },
    "timeframe": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/timeframe"
    },
    "fixed": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/fixed"
    },
    "weighted": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/weighted"
    },
    "stop_loss": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/stop_loss"
    },
    "trailing_stop": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/trailing_stop"
    },
    "take_profit": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/strategy_schema.json#/definitions/take_profit"
    },
    "reserved_vars" :{
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0
    },
    "vars": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/vars_schema.json#/definitions/vars"
    },
    "buy_sell_systems_pt_ga" : {
      "$ref": "http://ssel.asuscomm.com:9080/v1/systems_schema.json#/definitions/buy_sell_systems_pt_ga"
    },
    "buy_systems": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/systems_schema.json#/definitions/systems"
    },
    "buy_system_op": {
      "type": "string"
    },
    "sell_systems": {
      "$ref": "http://ssel.asuscomm.com:9080/v1/systems_schema.json#/definitions/systems"
    },
    "sell_system_op": {
      "type": "string"
    }
  },

  "required": ["stgy_name", "module_name", "bt_start", "bt_end", "markets","cdl_type", "init_balance", "slippage","vola", "timeframe", "fixed", "weighted", "stop_loss", "trailing_stop","take_profit","vars", "buy_systems", "buy_system_op"]
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/vol_bout_vol_pair_trading_ga.json
{
  "stgy_name": "VolatilityBreakoutStrategy",
  "module_name": "VolatilityBreakoutStrategy",
  "pt_exec" : true,
  "ga_exec" : true,
  "ga_exec_mode" : "BASIC",
  "ga_exec_obj" : "PROFIT",
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2022-11-25T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "ga_markets" : false,
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : [],
  "vola": {
    "support": true,
    "vol_tgt": 0.04,
    "ga_vol_tgt" : [0.02, 0.04]
  },
  "timeframe":{
    "support": false,
    "timeframes": ["07:59", "08:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "reserved_vars" : ["open_d1"],
  "vars": {
    "base_time" : "08:59",
    "ga_base_time" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                  "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                  "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                  "21:59", "22:59", "23:59"],
    "sell_time" : "07:59",
    "ga_sell_time" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                  "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                  "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                  "21:59", "22:59", "23:59"],
    "range": {"func": "range", "params": [1], "cdl_type": 1440, "sources": ["high","low"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "k", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "open_d1 + range * 0.5","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH",
        "ga_pt_left_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
        "ga_pt_right_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
        "ga_pt_tgt_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP"]}
  },
  "buy_system_op": "system1",
  "sell_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "sell_time"}
  },
  "sell_system_op": "system1"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/ws_day_vol_pair_trading_ga.json
{
  "stgy_name": "WS_PairTrading",
  "module_name": "WinningSessionStrategy",
  "pt_exec" : true,
  "ga_exec" : true,
  "ga_exec_mode" : "ADVANCED",
  "ga_exec_obj" : "PROFIT",
  "bt_start": "2020-01-01T08:59:00",
  "bt_end": "2022-03-31T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
  "ga_markets" : false,
  "cdl_type": 1440,
  "init_balance": 10000000,
  "slippage" : 0.0008,
  "bt_times" : ["08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": false,
    "timeframes": ["07:59", "08:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.10
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "ma": {"func": "sma", "params": [5], "cdl_type": 1440, "sources": ["close"], "unary": true,
      "ga_params": [[3,200, "Integer"]], "ga_cdl_types": [60, 240, 1440], "ga_sources" : ["open", "high", "low", "close"]}
  },
  "buy_systems": {
    "system1": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma",
        "pt_right_market" : "KRW-BTC",  "pt_tgt_market" : "KRW-ETH",
        "ga_pt_left_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_right_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_tgt_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"]
    },
    "system2": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma",
        "pt_right_market" : "KRW-ETH", "pt_tgt_market" : "KRW-XRP",
        "ga_pt_left_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_right_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_tgt_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"]
    },
    "system3": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-XRP", "op": ">", "right": "ma",
        "pt_right_market" : "KRW-XRP",  "pt_tgt_market" : "KRW-BTC",
        "ga_pt_left_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_right_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_tgt_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"]
    }
  },
  "buy_system_op": "system1 or system2 or system3",
  "sell_systems": {
    "system1": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma",
        "pt_right_market" : "KRW-BTC",  "pt_tgt_market" : "KRW-ETH",
        "ga_pt_left_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_right_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_tgt_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"]
    },
    "system2": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma",
        "pt_right_market" : "KRW-ETH", "pt_tgt_market" : "KRW-XRP",
        "ga_pt_left_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_right_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_tgt_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"]
    },
    "system3": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-XRP", "op": "<", "right": "ma",
        "pt_right_market" : "KRW-XRP",  "pt_tgt_market" : "KRW-BTC",
        "ga_pt_left_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_right_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"],
        "ga_pt_tgt_markets":  ["KRW-BTC", "KRW-ETH", "KRW-XRP", "KRW-ETC"]
    }
  },
  "sell_system_op": "system1 or system2 or system3"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/composite_bull_bear_market_pair_trading.json
{
  "stgy_name": "CompositeBullBearStrategy",
  "module_name": "CompositeStrategy",
  "pt_exec" : true,
  "bt_start": "2018-10-01T09:00:00",
  "bt_end": "2023-12-31T09:00:00",
  "markets": ["KRW-BTC", "KRW-ETH"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.005,
  "bt_times" : ["07:59", "08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.0306044914960572
  },
  "timeframe":{
    "support": false,
    "timeframes": ["7:59", "8:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "trade_time1" : "07:59",
    "trade_time2" : "08:59",
    "ma1": {"func": "sma", "params": [10], "cdl_type": 1440, "sources": ["low"], "unary": true},
    "ma2": {"func": "sma", "params": [8], "cdl_type": 1440, "sources": ["open"], "unary": true},
    "ma3": {"func": "sma", "params": [41], "cdl_type": 1440, "sources": ["open"], "unary": true},
    "ma4": {"func": "sma", "params": [62], "cdl_type": 1440, "sources": ["open"], "unary": true},
    "ma_decision": {"func": "sma", "params": [72], "cdl_type": 1440, "sources": ["low"], "unary": true}
  },
  "buy_systems": {
    "system1" :{"alias": "decision", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma_decision","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system2": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system3": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system4": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system5": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system6": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system7": {"alias": "time", "left": "time", "op": "==", "right": "trade_time1"},
    "system8": {"alias": "time", "left": "time", "op": "==", "right": "trade_time2"}
  },
  "buy_system_op": "(system1 and system2 and system3 and system4 and system5 and system6 and (system7 or system8)) or (not system1 and system2 and system3 and system4 and system5 and (system7 or system8))",
  "sell_systems": {
    "system1" :{"alias": "decision", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma_decision","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system2": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system3": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system4": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system5": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system6": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system7": {"alias": "time", "left": "time", "op": "==", "right": "trade_time1"},
    "system8": {"alias": "time", "left": "time", "op": "==", "right": "trade_time2"}
  },
  "sell_system_op": "(system1 and (system2 or system3 or system4 or system5 or system6) and (system7 or system8)) or (not system1 and (system2 or system3 or system4 or system5) and (system7 or system8))"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/ws_day_vol_pair_trading.json
{
  "stgy_name": "WS_PairTrading",
  "module_name": "WinningSessionStrategy",
  "pt_exec" : true,
  "bt_start": "2020-01-01T08:59:00",
  "bt_end": "2022-03-31T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "cdl_type": 1440,
  "init_balance": 10000000,
  "slippage" : 0.0008,
  "bt_times" : ["08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": false,
    "timeframes": ["07:59", "08:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.10
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "ma": {"func": "sma", "params": [5], "cdl_type": 1440, "sources": ["close"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma",
        "pt_right_market" : "KRW-BTC",  "pt_tgt_market" : "KRW-ETH"},
    "system2": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma",
        "pt_right_market" : "KRW-ETH", "pt_tgt_market" : "KRW-XRP"},
    "system3": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-XRP", "op": ">", "right": "ma",
        "pt_right_market" : "KRW-XRP",  "pt_tgt_market" : "KRW-BTC"}
  },
  "buy_system_op": "system1 or system2 or system3",
  "sell_systems": {
    "system1": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma",
        "pt_right_market" : "KRW-BTC",  "pt_tgt_market" : "KRW-ETH"},
    "system2": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma",
        "pt_right_market" : "KRW-ETH", "pt_tgt_market" : "KRW-XRP"},
    "system3": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-XRP", "op": "<", "right": "ma",
        "pt_right_market" : "KRW-XRP",  "pt_tgt_market" : "KRW-BTC"}
  },
  "sell_system_op": "system1 or system2 or system3"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/sws_ma_crossover_day_vol_pair_trading_ga2.json
{
  "stgy_name": "SuperWinningSessionPoweredByMACrossOver_Day",
  "module_name": "SuperWinningSessionStrategy",
  "pt_exec" : true,
  "ga_exec" : true,
  "ga_exec_mode" : "BEST_EFFORT",
  "ga_exec_obj" : "PROFIT",
  "bt_start": "2018-10-01T08:59:00",
  "bt_end": "2022-11-25T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "ga_markets" : false,
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.008,
  "bt_times" : ["07:59", "08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04,
    "ga_vol_tgt" : [0.02, 0.04]
  },
  "timeframe":{
    "support": false,
    "timeframes": ["7:59", "8:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "base_time" : "08:59",
    "ga_base_time" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                  "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                  "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                  "21:59", "22:59", "23:59"],
    "sell_time" : "07:59",
    "ga_sell_time" : ["00:59", "01:59", "02:59", "03:59", "04:59", "05:59","06:59",
                  "07:59", "08:59", "09:59", "10:59", "11:59", "12:59","13:59",
                  "14:59", "15:59", "16:59", "17:59", "18:59", "19:59","20:59",
                  "21:59", "22:59", "23:59"],
    "ma1": {"func": "sma", "params": [3], "cdl_type": 1440, "sources": ["close"], "unary": true,
            "ga_params": [[3,200, "Integer"]], "ga_cdl_types": [60, 240, 1440], "ga_sources" : ["open", "high", "low", "close"]},
    "ma2": {"func": "sma", "params": [5], "cdl_type": 1440, "sources": ["close"], "unary": true,
            "ga_params": [[3,200, "Integer"]], "ga_cdl_types": [60, 240, 1440], "ga_sources" : ["open", "high", "low", "close"]},
    "ma3": {"func": "sma", "params": [10], "ga_cdl_types": [60, 240, 1440], "cdl_type": 1440, "sources": ["close"], "unary": true,
            "ga_params": [[3,200, "Integer"]], "ga_cdl_types": [60, 240, 1440], "ga_sources" : ["open", "high", "low", "close"]},
    "ma4": {"func": "sma", "params": [20], "cdl_type": 1440, "sources": ["close"], "unary": true,
            "ga_params": [[3,200, "Integer"]], "ga_cdl_types": [60, 240, 1440], "ga_sources" : ["open", "high", "low", "close"]}},
  "buy_sell_systems_pt_ga" : {
    "ga_pt_left_markets" : ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
    "ga_pt_right_markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
    "ga_pt_tgt_markets"  : ["KRW-BTC", "KRW-ETH", "KRW-XRP"]
  },
  "buy_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "base_time"},
    "system2": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system3": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system4": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system5": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system6": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system7": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma1","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system8": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma2","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system9": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma3","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system10": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system11": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"}
  },
  "buy_system_op": "system1 and ((system2 and system3 and system4 and system5 and system6) or (system7 and system8 and system9 and system10 and system11))",
  "sell_systems": {
    "system1": {"alias": "time", "left": "time", "op": "==", "right": "sell_time"},
    "system2": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma1","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system3": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma2","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system4": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma3","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system5": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system6": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma4","pt_right_market" :  "KRW-BTC", "pt_tgt_market" :  "KRW-ETH"},
    "system7": {"alias": "ma1", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma1","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system8": {"alias": "ma2", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma2","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system9": {"alias": "ma3", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma3","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system10": {"alias": "ma4", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"},
    "system11": {"alias": "crossover", "left": "ma2", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma4","pt_right_market" :  "KRW-ETH", "pt_tgt_market" :  "KRW-BTC"}
  },
  "sell_system_op": "system1 and ((system2 or system3 or system4 or system5 or system6) or (system7 or system8 or system9 or system10 or system11))"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/ws_day_hdg_vol_pair_trading.json
{
  "stgy_name": "WS_Hdge_PairTrading",
  "module_name": "WinningSessionStrategy",
  "pt_exec" : true,
  "bt_start": "2020-01-01T08:59:00",
  "bt_end": "2022-03-31T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "cdl_type": 60,
  "init_balance": 10000000,
  "slippage" : 0.0008,
  "bt_times" : ["08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": true,
    "timeframes": ["08:59", "17:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": true,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.02
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "ma1": {"func": "sma", "params": [5], "cdl_type": 1474, "sources": ["close"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-BTC", "op": ">", "right": "ma1",
        "pt_right_market" : "KRW-BTC",  "pt_tgt_market" : "KRW-ETH"},
    "system2": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-ETH", "op": ">", "right": "ma1",
        "pt_right_market" : "KRW-ETH", "pt_tgt_market" : "KRW-XRP"},
    "system3": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-XRP", "op": ">", "right": "ma1",
        "pt_right_market" : "KRW-XRP",  "pt_tgt_market" : "KRW-BTC"}
  },
  "buy_system_op": "system1 or system2 or system3",
  "sell_systems": {
    "system1": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-BTC", "op": "<", "right": "ma1",
        "pt_right_market" : "KRW-BTC",  "pt_tgt_market" : "KRW-ETH"},
    "system2": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-ETH", "op": "<", "right": "ma1",
        "pt_right_market" : "KRW-ETH", "pt_tgt_market" : "KRW-XRP"},
    "system3": {"alias": "ma", "left": "close", "pt_left_market" : "KRW-XRP", "op": "<", "right": "ma1",
        "pt_right_market" : "KRW-XRP",  "pt_tgt_market" : "KRW-BTC"}
  },
  "sell_system_op": "system1 or system2 or system3"
}

=== Jung-YongHan/GenTradingRuleWithGP/src/trader/bt4_cfg_stgy_rules/ws_day_vol_pair_trading_using_spread.json
{
  "stgy_name": "WS_PairTrading",
  "module_name": "WinningSessionStrategy",
  "pt_exec" : true,
  "bt_start": "2020-01-01T08:59:00",
  "bt_end": "2022-03-31T08:59:00",
  "markets": ["KRW-BTC", "KRW-ETH", "KRW-XRP"],
  "cdl_type": 1440,
  "init_balance": 10000000,
  "slippage" : 0.0008,
  "bt_times" : ["08:59"],
  "vola": {
    "support": true,
    "vol_tgt": 0.04
  },
  "timeframe":{
    "support": false,
    "timeframes": ["07:59", "08:59"],
    "timegap": 1
  },
  "fixed": {
    "support": false,
    "hdge": false,
    "trade_ratio": 0.4
  },
  "weighted": {
    "support": false,
    "top_n": [0.6,0.3,0.1]
  },
  "stop_loss": {
    "support": false,
    "ratio": -0.04
  },
  "trailing_stop": {
    "support": false,
    "ratio": -0.10
  },
  "take_profit": {
    "support": false,
    "ratio": 0.07
  },
  "vars": {
    "spread1": {"func": "spread", "params": ["upbit", "KRW-BTC", "KRW-ETH", 50], "cdl_type": 1440, "sources": ["close"], "unary": true},
    "spread2": {"func": "spread", "params": ["upbit", "KRW-ETH", "KRW-BTC", 50], "cdl_type": 1440, "sources": ["close"], "unary": true}
  },
  "buy_systems": {
    "system1": {"alias": "spread1", "left": "spread1", "left_market" : "KRW-BTC", "op": ">", "right": "5",
        "right_market" : "KRW-BTC",  "tgt_market" : "KRW-ETH"},
    "system2": {"alias": "spread2", "left": "spread2", "left_market" : "KRW-ETH", "op": ">", "right": "5",
        "right_market" : "KRW-ETH", "tgt_market" : "KRW-BTC"}
  },
  "buy_system_op": "system1 or system2",
  "sell_systems": {
    "system1": {"alias": "spread1", "left": "spread", "left_market" : "KRW-BTC", "op": "<", "right": "5",
        "right_market" : "KRW-BTC",  "tgt_market" : "KRW-ETH"},
    "system2": {"alias": "spread2", "left": "spread", "left_market" : "KRW-ETH", "op": "<", "right": "5",
        "right_market" : "KRW-ETH", "tgt_market" : "KRW-BTC"}
  },
  "sell_system_op": "system1 or system2 or system3"
}
